### ISSUE TITLE
Odd behaviour for Elixir umbrella apps. Not sure how to debug.

### ISSUE THREAD

**Issue by georgeguimaraes** [Wansmer/symbol-usage.nvim#22]
Thanks for the plugin! I was looking for something like this to help me navigate our codebase.

Not sure how to describe it, but I found an odd behaviour when dealing with Elixir umbrella apps. Umbrella apps are like monorepos. You have different "apps" that can reference Modules from other apps. For instance (real codebase):

```
analytics/
├── .git/
├── mix.exs
├── config/
└── apps/
    ├── analytics_web/
    │   ├── mix.exs
    │   └── lib/
    │       └── analytics_web/
    │           └── controllers/
    │               └── invitation_controller.ex # uses Analytics.Invitations.remove_member
    └── analytics/
        ├── mix.exs
        └── lib/
            └── analytics/
                └── invitations.ex  # has the definition for Analytics.Invitations.remove_member(...)  
```

My LSP root is set to the root umbrella folder, so LSP can see the whole structure.

`symbol-usage` can count references within an app itself (like in the same file, for instance). However, when we cross the boundary of the apps, I got "**no usage**":

![CleanShot 2023-10-15 at 18 45 27@2x](https://github.com/Wansmer/symbol-usage.nvim/assets/2929/5501a981-48c0-4645-9f19-fcdfe98b6409)

I can run `:lua vim.lsp.buf.references()` and indeed LSP get the correct reference from the other app inside my umbrella:

![CleanShot 2023-10-15 at 18 58 31@2x](https://github.com/Wansmer/symbol-usage.nvim/assets/2929/d3ff4c97-d809-4106-9eea-1d4bb5c14433)

I tried to debug this further and found out that if I change the logic in https://github.com/Wansmer/symbol-usage.nvim/blob/main/lua/symbol-usage/utils.lua#L89 to use the  `start` of  `selectionRange`, instead of `end`, symbol-usage can reference correctly and show me **"1 usage":**

![CleanShot 2023-10-15 at 18 46 15@2x](https://github.com/Wansmer/symbol-usage.nvim/assets/2929/bc0d73ef-e062-4814-9335-3018089380cb)

I'm not sure why selectionRange.end is used there, but should it be selectionRange.start, so that the LSP can identify the symbol? Or is this behaviour probably related to `elixirls`?

Happy to help with more debugging.

**Comment by Wansmer** [comment]
Thanks for the detailed issue!

The `selectionRange.end` is used to avoid incorrect counting in the case of lua methods (e.g. `M:something()` - when `start` was used here, it counted the number of `M` instead of `something`). I tested `end` in several languages (lua, js/ts, rust and go) and it worked correctly in all cases (except for bash_ls, where `selectionRange` didn't appear at all).

The lsp of elexir seems to give different data. I'll think about how to handle this case.

**Comment by georgeguimaraes** [comment]
> symbol-usage can count references within an app itself (like in the same file, for instance).

I take that back, I misunderstood what I was seeing.

The only functions that get counted are functions without arguments, like:
 ```
def redeem_deadline do
  # ...
end
 ```

In this case,  `vim.lsp.buf.references()` work as expected from the "r" until the blank space before "do".

In Elixir, function declaration can become pretty wild:

```
  defp update_invitation(invitation, _attrs) when is_nil(invitation) do
    {:error, "Invitation does not exist"}
  end
 ```

In this case,  if the cursor is on "is_nil" and I invoke `vim.lsp.buf.references()`, it lists all the occurences of is_nil in the codebase. If I invoke it on the last closing parentheses "invitation)", it doesn't show anything.

**Comment by georgeguimaraes** [comment]
> The lsp of elexir seems to give different data. I'll think about how to handle this case

Thanks!

**Comment by Wansmer** [comment]
I added the `symbol_request_pos` option to the config. Try to update the plugin and add the following to your config for elixir:

```lua
require('symbol-usage').setup({
  filetypes = {
    elixir = {
      symbol_request_pos = 'start',
    },
  },
})
```

**Comment by georgeguimaraes** [comment]
Thanks @Wansmer. It is working :)
