### ISSUE TITLE
Bug: `toggle` api has some bugs

### ISSUE THREAD

**Issue by OliverChao** [Wansmer/symbol-usage.nvim#32]
Hey, this is a wonderful plugins.
But I got some bugs when using `toggle` api.
The first time executing `toggle`, `symbol-usage` stops to counting but the virtual texts still exist.
And the second time executing it  clears the virtual texts.

https://github.com/Wansmer/symbol-usage.nvim/assets/39361033/0e7452a3-6e09-4ebe-99e3-e419e3846a54

I don't know if somebody reproduces that. I use neovim with latest version(NVIM v0.10.0-dev-1846+gf31f260f0) on MacOS(M2).

I install it using lazy:
```lua
 {
  "Wansmer/symbol-usage.nvim",
  -- event = "LspAttach", -- need run before LspAttach if you use nvim 0.9. On 0.10 use 'LspAttach'
  opts = {
    vt_position = "end_of_line",
  },
}

```

**Comment by OliverChao** [comment]
hey, I checked some code and pushed one  pr https://github.com/Wansmer/symbol-usage.nvim/pull/33.
That pr fix some problems.
With https://github.com/Wansmer/symbol-usage.nvim/pull/33,   `:lua require('symbol-usage').toggle()` in command line works. 
It is fine for me.

==============

But it in command history panel, it fails.
I checked the code and found that this problem was caused by `BufEnter` autocmd.
Running toggle api in command history panel always make buf `worker` alive once, even deleting it by `state.remove_buffer(bufnr)`.

==============

Anyway , Using `:lua require('symbol-usage').toggle()` in command line only and I make one map for this api works fine for me with pr https://github.com/Wansmer/symbol-usage.nvim/pull/33.

**Comment by Wansmer** [comment]
Hi, thanks for the PR, it fixes the bug with checking for nil.

> But it in command history panel, it fails.
> I checked the code and found that this problem was caused by BufEnter autocmd.

Yes, you are right. It seems that `ButEnter` is triggered before the handlers are cleared. I think this is easily solved by wrapping `clear_buffer` in `vim.schedule()` - I'll experiment and add it later. 

I'll keep the issue open until I solve the problem with calling from the command history.

**Comment by OliverChao** [comment]
Thanks for your work.
