### ISSUE TITLE
Feature request: file blacklist regex

### ISSUE THREAD

**Issue by anuramat** [Wansmer/symbol-usage.nvim#36]
This plugin pretty much breaks any interaction with LSP on (large) generated (e.g. protobuf `*.pb.go`) files when using gopls - server hangs up. Could be remedied by a simple blacklist regex.

**Comment by Wansmer** [comment]
In #39 I added a `disable.cond` list where you can specify with function on which buffers symbol-usage should not be run.

In your case is:
```lua
require("symbol-usage").setup({
  disable = {
    cond = {
      function()
        return vim.fn.expand("%:p"):match("%.pb%.go$")
      end,
    },
  },
})
```
