### ISSUE TITLE
[Other | Optimize ]:  flashing screen and lagging

### ISSUE THREAD

**Issue by mochouaaaaa** [Wansmer/symbol-usage.nvim#38]
Hi! Thanks for the great plugin.
When using lsp gd, jumping to the source code the plugin should not load the information because the user does not necessarily care about the references in the source code.

It can be filtered out by lsp root_dir to not load relationships outside of the working directory.

<img width="2038" alt="loading " src="https://github.com/Wansmer/symbol-usage.nvim/assets/30570532/53b5ecdd-5cd7-4468-b021-66fd8988fbdf">

**Comment by Wansmer** [comment]
> Hi! Thanks for the great plugin.

Hi! Thanks for the feedback!
In #39 I added a `disable.cond` list where you can specify with function on which buffers `symbol-usage` should not be run.

E.g.:

```lua
require("symbol-usage").setup({
  disable = {
    cond = {
      function()
        -- disable for all files in node_modules
        return vim.fn.expand("%:p"):find("/node_modules/")
      end,
      function()
        -- disable for all files outside of the cwd
        return vim.fn.expand("%:p"):find(vim.fn.getcwd())
      end,
    },
  },
})
```
