### ISSUE TITLE
Error when closing buffer before loading `LSP` client

### ISSUE THREAD

**Issue by Green0wl** [Wansmer/symbol-usage.nvim#40]
https://github.com/Wansmer/symbol-usage.nvim/assets/72041440/eacb65c7-9ac8-42fd-9b43-6497c53b0119

I get an error when closing a buffer that has any functions in it before loading the `LSP` client. I close the buffer via `:Bdelete<cr>`. Thank you in advance

**Comment by Wansmer** [comment]
I can't reproduce this bug with embedded `:bd` and `:bw`, because I don't know what the plugin provides `:Bdelete` and how this command works. 

Does this reproducer with minimal config (clean nvim with only `symobl-usage` plugin)? What version of the neovim are you using?

**Comment by Green0wl** [comment]
I use [this](https://github.com/moll/vim-bbye) plugin to get `:Bdelete`. Regarding the minimum configuration - I haven't checked. The version of neovim that I'm using is `0.9.1`.

**Comment by Green0wl** [comment]
I checked your variant with `:bw` and `:bd` and found that the error appears only with `:bd` and if you close the tab for the first time (i.e. right after starting `nvim`). otherwise the error does not appear. probably because the `LSP` client is already running.
