### ISSUE TITLE
FR: make sign priority configurable to manage conflicts with other signs

### ISSUE THREAD

**Issue by chrisgrieser** [Wansmer/symbol-usage.nvim#61]
I recently tried out `signcolumn` as display method and I actually like it very much. 

It looks like when there is a symbol count as well as a gitsign for the same line, the gitsign takes priority (which is good). However, specifically in css files, the symbol count takes priority over gitsigns. From all the filetypes I use, this apparently only affects css files. I tried changing the `sign_priority` setting from gitsigns, but it did not make any difference. (and it would affect all filetypes anyway, so I am not sure why the priority only changes for one specific filetype.)

**Comment by Wansmer** [comment]
The `symbol-usage` does not control the display priority in the `signcolumn` in any way, so I don't think it's right to address this issue here.

Perhaps this behavior is related to the loading speed of the css server. Apparently in this case `cssls` just fires later than `gitsigns`.

**Comment by chrisgrieser** [comment]
> The symbol-usage does not control the display priority in the signcolumn in any way, so I don't think it's right to address this issue here.

What you describe sounds like the issue can only be resolved by giving the symbols a higher priority than gitsigns, which is something which can only be done in the `set_extmark` call of this plugin, if I am not mistaken?

**Comment by Wansmer** [comment]
You mean you'd like to see the ability to manage options for `nvim_set_extmark` in the plugin?

If so, this is a `feature request`, not a `bug` ))

**Comment by chrisgrieser** [comment]
With the knowledge I had at the time of submitting the issue, it appeared to be a bug though ;)

But yes, with the current knowledge, it's technically more a FR than a bug

**Comment by Wansmer** [comment]
Done #62

**Comment by chrisgrieser** [comment]
Thanks you!
